// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEhXjYNVqmkOmBlLY-ZdIpmb4Lc1_FaE0',
    appId: '1:663776273324:web:0088906d21e04f05be5009',
    messagingSenderId: '663776273324',
    projectId: 'flutter-kpsr',
    authDomain: 'flutter-kpsr.firebaseapp.com',
    storageBucket: 'flutter-kpsr.firebasestorage.app',
    measurementId: 'G-QXML1G55WQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt8YnRsKOQqm61E51KQWH6vfMuch6DHkQ',
    appId: '1:663776273324:android:cd664b2ad8162a69be5009',
    messagingSenderId: '663776273324',
    projectId: 'flutter-kpsr',
    storageBucket: 'flutter-kpsr.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANo9A9dZLDVJ9uikZ28wIfANCQLb2ETPo',
    appId: '1:663776273324:ios:cfd2a96be0a6ccccbe5009',
    messagingSenderId: '663776273324',
    projectId: 'flutter-kpsr',
    storageBucket: 'flutter-kpsr.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANo9A9dZLDVJ9uikZ28wIfANCQLb2ETPo',
    appId: '1:663776273324:ios:cfd2a96be0a6ccccbe5009',
    messagingSenderId: '663776273324',
    projectId: 'flutter-kpsr',
    storageBucket: 'flutter-kpsr.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEhXjYNVqmkOmBlLY-ZdIpmb4Lc1_FaE0',
    appId: '1:663776273324:web:843a463d3599b660be5009',
    messagingSenderId: '663776273324',
    projectId: 'flutter-kpsr',
    authDomain: 'flutter-kpsr.firebaseapp.com',
    storageBucket: 'flutter-kpsr.firebasestorage.app',
    measurementId: 'G-E1MZN7QL4P',
  );

}